**1) NLTK**

	NLTK is a Python library used in natural language processing (NLP) for tasks such as tokenization and text processing. The code example shows how you can tokenize text using the NLTK word-based tokenizer.

In [1]:
import nltk
nltk.download("punkt")
from nltk.tokenize import word_tokenize
text = "Unicorns are real. I saw a unicorn yesterday. I couldn't see it today."
token = word_tokenize(text)
print(token)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['Unicorns', 'are', 'real', '.', 'I', 'saw', 'a', 'unicorn', 'yesterday', '.', 'I', 'could', "n't", 'see', 'it', 'today', '.']


**2) spaCy**

spaCy is an open-source library used in NLP. It provides tools for tasks such as tokenization and word embeddings. The code example shows how you can tokenize text using spaCy word-based tokenizer.

In [2]:
import spacy
text = "Unicorns are real. I saw a unicorn yesterday. I couldn't see it today."
nlp = spacy.load("en_core_web_sm")
doc = nlp(text)
token_list = [token.text for token in doc]
print("Tokens:", token_list)

Tokens: ['Unicorns', 'are', 'real', '.', 'I', 'saw', 'a', 'unicorn', 'yesterday', '.', 'I', 'could', "n't", 'see', 'it', 'today', '.']


**3) BertTokenizer**

BertTokenizer is a subword-based tokenizer that uses the WordPiece algorithm. The code example shows how you can tokenize text using BertTokenizer.

In [3]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer.tokenize("IBM taught me tokenization.")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

['ibm', 'taught', 'me', 'token', '##ization', '.']

**4) XLNetTokenizer**

XLNetTokenizer tokenizes text using Unigram and SentencePiece algorithms. The code example shows how you can tokenize text using XLNetTokenizer.

In [4]:
from transformers import XLNetTokenizer
tokenizer = XLNetTokenizer.from_pretrained("xlnet-base-cased")
tokenizer.tokenize("IBM taught me tokenization.")

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

['▁IBM', '▁taught', '▁me', '▁token', 'ization', '.']

**5) torchtext**

The torchtext library is part of the PyTorch ecosystem and provides the tools and functionalities required for NLP. The code example shows how you can use torchtext to generate tokens and convert them to indices.

In [5]:
from torchtext.vocab import build_vocab_from_iterator
# Defines a dataset
dataset = [
    (1,"Introduction to NLP"),
    (2,"Basics of PyTorch"),
    (1,"NLP Techniques for Text Classification"),
    (3,"Named Entity Recognition with PyTorch"),
    (3,"Sentiment Analysis using PyTorch"),
    (3,"Machine Translation with PyTorch"),
    (1,"NLP Named Entity,Sentiment Analysis, Machine Translation"),
    (1,"Machine Translation with NLP"),
    (1,"Named Entity vs Sentiment Analysis NLP")]
# Applies the tokenizer to the text to get the tokens as a list
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer("basic_english")
tokenizer(dataset[0][1])
# Takes a data iterator as input, processes text from the iterator,
# and yields the tokenized output individually
def yield_tokens(data_iter):
    for _,text in data_iter:
        yield tokenizer(text)
# Creates an iterator
my_iterator = yield_tokens(dataset)
# Fetches the next set of tokens from the data set
next(my_iterator)
# Converts tokens to indices and sets <unk> as the
# default word if a word is not found in the vocabulary
vocab = build_vocab_from_iterator(yield_tokens(dataset), specials=["<unk>"])
vocab.set_default_index(vocab["<unk>"])
# Gives a dictionary that maps words to their corresponding numerical indices
vocab.get_stoi()

/usr/local/lib/python3.10/dist-packages/torchtext/vocab/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/usr/local/lib/python3.10/dist-packages/torchtext/utils.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/usr/local/lib/python3.10/dist-packages/torchtext/data/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated

{'vs': 21,
 'to': 19,
 'of': 15,
 'introduction': 14,
 'recognition': 16,
 'for': 13,
 'nlp': 1,
 'entity': 4,
 'pytorch': 2,
 'translation': 8,
 'techniques': 17,
 'machine': 5,
 'named': 6,
 ',': 10,
 'text': 18,
 'sentiment': 7,
 '<unk>': 0,
 'with': 9,
 'basics': 11,
 'using': 20,
 'analysis': 3,
 'classification': 12}

**6) vocab**

The vocab object is part of the PyTorch torchtext library. It maps tokens to indices. The code example shows how you can apply the vocab object to tokens directly.

In [6]:
# Takes an iterator as input and extracts the next tokenized sentence.
# Creates a list of token indices using the vocab dictionary for each token.
def get_tokenized_sentence_and_indices(iterator):
    tokenized_sentence = next(iterator)
    token_indices = [vocab[token] for token in tokenized_sentence]
    return tokenized_sentence, token_indices
# Returns the tokenized sentences and the corresponding token indices.
# Repeats the process.
tokenized_sentence, token_indices = \
get_tokenized_sentence_and_indices(my_iterator)
next(my_iterator)
# Prints the tokenized sentence and its corresponding token indices.
print("Tokenized Sentence:", tokenized_sentence)
print("Token Indices:", token_indices)

Tokenized Sentence: ['basics', 'of', 'pytorch']
Token Indices: [11, 15, 2]


Special tokens in PyTorch: <eos> and <bos>**bold text**

Special tokens are tokens introduced to input sequences to convey specific information or serve a particular purpose during training. The code example shows the use of <bos> and <eos> during tokenization. The <bos> token denotes the beginning of the input sequence, and the <eos> token denotes the end.

In [18]:
# Appends <bos> at the beginning and <eos> at the end of the tokenized sentences
# using a loop that iterates over the sentences in the input data
lines = ["This is the first sentence.", "Here is another one.", "This one is shorter."]
tokenizer_en = get_tokenizer('spacy', language='en_core_web_sm')
tokens = []
max_length = 0
for line in lines:
    tokenized_line = tokenizer_en(line)
    tokenized_line = ['<bos>'] + tokenized_line + ['<eos>']
    tokens.append(tokenized_line)
    max_length = max(max_length, len(tokenized_line))
print("Tokenized sentences with <bos> and <eos> tokens:")
for tokenized_line in tokens:
    print(tokenized_line)

print("\nMaximum length of tokenized sentences:", max_length)

Tokenized sentences with <bos> and <eos> tokens:
['<bos>', 'This', 'is', 'the', 'first', 'sentence', '.', '<eos>']
['<bos>', 'Here', 'is', 'another', 'one', '.', '<eos>']
['<bos>', 'This', 'one', 'is', 'shorter', '.', '<eos>']

Maximum length of tokenized sentences: 8


Special tokens in PyTorch: <pad>**bold text**

The code example shows the use of <pad> token to ensure all sentences have the same length.

In [8]:
# Pads the tokenized lines
for i in range(len(tokens)):
    tokens[i] = tokens[i] + ['<pad>'] * (max_length - len(tokens[i]))

**Dataset class in Pytorch**

The Dataset class enables accessing and retrieving individual samples from a data set. The code example shows how you can create a custom data set and access samples.

In [11]:
# Imports the Dataset class and defines a list of sentences
from torch.utils.data import Dataset
sentences = ["If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "Fae's a fickle friend, Harry."]
# Downloads and reads data
class CustomDataset(Dataset):
    def __init__(self, sentences):
        self.sentences = sentences
    # Returns the data length
    def __len__(self):
        return len(self.sentences)
    # Returns one item on the index
    def __getitem__(self, idx):
        return self.sentences[idx]
# Creates a dataset object
dataset=CustomDataset(sentences)
# Accesses samples like in a list
dataset[0]

"If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals."

**DataLoader class in PyTorch**

A DataLoader class enables efficient loading and iteration over data sets for training deep learning models. The code example shows how you can use the DataLoader class to generate batches of sentences for further processing, such as training a neural network model

In [16]:
import torch
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence

# Mock implementations of tokenizer and vocab
def tokenizer(sample):
    return sample.split()

vocab = {'hello': 1, 'world': 2, '<pad>': 0}

# Custom dataset implementation
class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Define the collate function
def collate_fn(batch):
    tensor_batch = []
    # Tokenizes each sample in the batch
    for sample in batch:
        tokens = tokenizer(sample)
        # Maps tokens to numbers using the vocab
        tensor_batch.append(torch.tensor([vocab.get(token, 0) for token in tokens], dtype=torch.long))
    # Pads the sequences within the batch to have equal lengths
    padded_batch = pad_sequence(tensor_batch, batch_first=True, padding_value=vocab['<pad>'])
    return padded_batch

# Create an instance of the custom dataset
sentences = ["hello world", "hello", "world world hello"]
custom_dataset = CustomDataset(sentences)

# Specify batch size
batch_size = 2

# Create a DataLoader with the custom collate function
dataloader = DataLoader(custom_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)

# Create an iterator object
data_iter = iter(dataloader)

# Retrieve and print the first batch of samples
print(next(data_iter))

# Iterate over the data loader and print the sentences in each batch
for batch in dataloader:
    print(batch)


tensor([[2, 2, 1],
        [1, 0, 0]])
tensor([[1, 2, 0],
        [2, 2, 1]])
tensor([[1]])


**Custom collate function in PyTorch**

The custom collate function is a user-defined function that defines how individual samples are collated or batched together. You can utilize the collate function for tasks such as tokenization, converting tokenized indices, and transforming the result into a tensor. The code example shows how you can use a custom collate function in a data loader.

In [15]:
import torch
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence

# Mock implementations of tokenizer and vocab
def tokenizer(sample):
    return sample.split()

vocab = {'hello': 1, 'world': 2, '<pad>': 0}

# Custom dataset implementation
class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Define the collate function
def collate_fn(batch):
    tensor_batch = []
    # Tokenizes each sample in the batch
    for sample in batch:
        tokens = tokenizer(sample)
        # Maps tokens to numbers using the vocab
        tensor_batch.append(torch.tensor([vocab.get(token, 0) for token in tokens], dtype=torch.long))
    # Pads the sequences within the batch to have equal lengths
    padded_batch = pad_sequence(tensor_batch, batch_first=True, padding_value=vocab['<pad>'])
    return padded_batch

# Create an instance of the custom dataset
data = ["hello world", "hello", "world world hello"]
custom_dataset = CustomDataset(data)

# Define batch size
batch_size = 2

# Create a data loader using the collate function and the custom dataset
dataloader = DataLoader(custom_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)

# Iterate over the data loader and print the batch
for batch in dataloader:
    print(batch)


tensor([[1, 0],
        [1, 2]])
tensor([[2, 2, 1]])
